-- MySQL Script generated by MySQL Workbench
-- Mon Jul 20 19:08:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DBOFF1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBOFF1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBOFF1` DEFAULT CHARACTER SET utf8 ;
USE `DBOFF1` ;

-- -----------------------------------------------------
-- Table `DBOFF1`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOFF1`.`Brands` (
  `brands_id` INT NOT NULL AUTO_INCREMENT,
  `brands_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`brands_id`));


-- -----------------------------------------------------
-- Table `DBOFF1`.`Grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOFF1`.`Grades` (
  `grades_id` TINYINT NOT NULL AUTO_INCREMENT,
  `grades` CHAR(1) NOT NULL,
  PRIMARY KEY (`grades_id`));


-- -----------------------------------------------------
-- Table `DBOFF1`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOFF1`.`Products` (
  `code` INT NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `Brands_brands_id` INT NOT NULL,
  `Grades_grades_id` TINYINT NOT NULL,
  PRIMARY KEY (`code`, `Brands_brands_id`, `Grades_grades_id`),
  INDEX `fk_Products_Brands1_idx` (`Brands_brands_id` ASC) VISIBLE,
  INDEX `fk_Products_Grades1_idx` (`Grades_grades_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Brands1`
    FOREIGN KEY (`Brands_brands_id`)
    REFERENCES `DBOFF1`.`Brands` (`brands_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Grades1`
    FOREIGN KEY (`Grades_grades_id`)
    REFERENCES `DBOFF1`.`Grades` (`grades_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `DBOFF1`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOFF1`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `DBOFF1`.`Searches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOFF1`.`Searches` (
  `searches_id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL,
  `Users_user_id` INT NOT NULL,
  `Products_code` INT NOT NULL,
  PRIMARY KEY (`searches_id`, `Users_user_id`, `Products_code`),
  INDEX `fk_Searches_Users_idx` (`Users_user_id` ASC) VISIBLE,
  INDEX `fk_Searches_Products1_idx` (`Products_code` ASC) VISIBLE,
  CONSTRAINT `fk_Searches_Users`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `DBOFF1`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Searches_Products1`
    FOREIGN KEY (`Products_code`)
    REFERENCES `DBOFF1`.`Products` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `DBOFF1`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOFF1`.`Categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `DBOFF1`.`Searches_saved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOFF1`.`Searches_saved` (
  `searches_saved_id` INT NOT NULL AUTO_INCREMENT,
  `Users_user_id` INT NOT NULL,
  `Products_code` INT NOT NULL,
  PRIMARY KEY (`searches_saved_id`, `Users_user_id`, `Products_code`),
  INDEX `fk_Searches_saved_Users1_idx` (`Users_user_id` ASC) VISIBLE,
  INDEX `fk_Searches_saved_Products1_idx` (`Products_code` ASC) VISIBLE,
  CONSTRAINT `fk_Searches_saved_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `DBOFF1`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Searches_saved_Products1`
    FOREIGN KEY (`Products_code`)
    REFERENCES `DBOFF1`.`Products` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `DBOFF1`.`Stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOFF1`.`Stores` (
  `stores_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`stores_id`));


-- -----------------------------------------------------
-- Table `DBOFF1`.`Products_has_Stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOFF1`.`Products_has_Stores` (
  `Products_code` INT NOT NULL,
  `Products_Brands_brands_id` INT NOT NULL,
  `Products_Grades_grades_id` TINYINT NOT NULL,
  `Stores_stores_id` INT NOT NULL,
  PRIMARY KEY (`Products_code`, `Products_Brands_brands_id`, `Products_Grades_grades_id`, `Stores_stores_id`),
  INDEX `fk_Products_has_Stores_Stores1_idx` (`Stores_stores_id` ASC) VISIBLE,
  INDEX `fk_Products_has_Stores_Products1_idx` (`Products_code` ASC, `Products_Brands_brands_id` ASC, `Products_Grades_grades_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Stores_Products1`
    FOREIGN KEY (`Products_code` , `Products_Brands_brands_id` , `Products_Grades_grades_id`)
    REFERENCES `DBOFF1`.`Products` (`code` , `Brands_brands_id` , `Grades_grades_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Stores_Stores1`
    FOREIGN KEY (`Stores_stores_id`)
    REFERENCES `DBOFF1`.`Stores` (`stores_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `DBOFF1`.`Products_has_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBOFF1`.`Products_has_Categories` (
  `Products_code` INT NOT NULL,
  `Products_Brands_brands_id` INT NOT NULL,
  `Products_Grades_grades_id` TINYINT NOT NULL,
  `Categories_category_id` INT NOT NULL,
  PRIMARY KEY (`Products_code`, `Products_Brands_brands_id`, `Products_Grades_grades_id`, `Categories_category_id`),
  INDEX `fk_Products_has_Categories_Categories1_idx` (`Categories_category_id` ASC) VISIBLE,
  INDEX `fk_Products_has_Categories_Products1_idx` (`Products_code` ASC, `Products_Brands_brands_id` ASC, `Products_Grades_grades_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Categories_Products1`
    FOREIGN KEY (`Products_code` , `Products_Brands_brands_id` , `Products_Grades_grades_id`)
    REFERENCES `DBOFF1`.`Products` (`code` , `Brands_brands_id` , `Grades_grades_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Categories_Categories1`
    FOREIGN KEY (`Categories_category_id`)
    REFERENCES `DBOFF1`.`Categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
